driver:
  name: ec2
  aws_ssh_key_id: AWS-Default
  security_group_ids: ["sg-28c43247"]
  region: eu-west-1
  require_chef_omnibus: true
  subnet_id: subnet-35a1565f
  associate_public_ip: true
  instance_type: t2.nano
#  interface: private
  shared_credentials_profile: <%= ENV['AWS_PROFILE'] %>
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID_QA'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY_QA'] %>

transport:
  ssh_key: /Users/grifonas/keys/AWS-Default.pem
  username: ubuntu

provisioner:
  name: chef_solo

platforms:
  - name: amazon
    driver:
      image_id: ami-6f587e1c
      tags:
        Name: NodeApp1-ChefKitchen-Tests
        CycleStatus: Tests
        created-by: test-kitchen
      
suites:
  - name: default
    run_list:
      - recipe[nodejs::jenkins_user]
    attributes:
